_format_version: "2.1"
_transform: true


# Config Consumers and JWT for consumers

consumers:
- username: gmm

jwt_secrets:
- consumer: gmm
  algorithm: RS256
  key: GAE
  rsa_public_key: "-----BEGIN PUBLIC KEY-----\nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA1MtRnSG0FT5BvJWjrieH\nesissdmUVsxal/p8s+2AiV+TtxI2R6PGnFMMOsz1s3/Xs5cMdYml1voKowHNF0+x\nhMO63vh+VfQOOI4TLAQMAMJgacftWEuuj7PbZfER6hu4xtKhJyMxISKrhEkMhkNb\nr652clLP+elWjiHNnk5J6rzyj7WZmjeQIZafRtWkPhlOxlHJV/8iaIZwZ/igvAhh\nr8Hls0b6E5Y4BA1oCMhelSffUj/aGAQwAagUkRhY6SMJ00oMfk4WAXLLcAtPHMeG\nvRxMHawBddSr4ozNdqtVjNrWfK18r4o8sAc709rtdGdwLUlBgQQTovFc985A4rQ3\nOdVz0O0umT0WygSyOfnQPIea/ixuekYUl4O5uQie8WErh1STEYPZk0I0Rt5/fwYX\n6R5uHIIhU5M3GQXQoy8gnWzDhyeNnkxPT04a6QhdXMOPA+8ORcKtXONpgZMLZBAP\nK8egK6LxfRxLJ5vtnGbzgnZj7J5MiizsZDn3b80R8pltynEkKiPmALuVbuz6iEie\nON8TDCSI5R0VLr1AJXfjDJD7bS6WaIaB31HHfUtEZImD88VzgddqNBLcwy28IUBF\nwnoyjZPwlxQxJaOqBecR7zZrHYRHK0MjV9PHJB3X+m0R7JWpxhjjhdbuiANV3xNg\ngI7Qy8bSZgHl4DE5OdxheWsCAwEAAQ==\n-----END PUBLIC KEY-----\n%"

plugins:
- name: jwt
  enabled: yes
  service: api-service
  config:
    secret_is_base64: false
    header_names: ["Authorization"]
    key_claim_name: iss
    run_on_preflight: true
    claims_to_verify:
      - exp

- name: rate-limiting
  config:
    second: 5
    hour: 10000
    policy: local
    fault_tolerant: true
    hide_client_headers: false
    redis_ssl: false
    redis_ssl_verify: false

# Config for Proxy cache request
- name: proxy-cache
  config:
    response_code:
    - 200
    request_method:
    - GET
    - HEAD
    content_type:
    - text/plain
    - application/json
    cache_ttl: 300
    strategy: memory

# Config Services và Routes
certificates:
  - snis:
      - name: gae-gw.systems
    key: "-----BEGIN RSA PRIVATE KEY-----\nMIIEogIBAAKCAQEA4H+5aJUq+83BATH2gyHqhMpQaCAy50sQky4P59eSshJmyo5k\nLzRPXbGNvbgkSU1bYfym96xeKNE2/VldODSzHUGUBYkiW77lhvnxXskzaV2MwUe0\nxfSmDlC4F3IY7ClTVhE0++eaGzX2S75dRNXf8kHJ/mceuG1riAV+3OFGAziKrRx2\nqY/YVO6gDHu6GaPqNTGOol23S8dyfnNsvpF28UiESshuxNbF3PWQ4FXlEh8AEllt\nkWE5UndYibnxkeLSvIjPI4yeN5KvldsSTcCCKxfMSqGkLada1dAzb/vsm/I4IGnh\nYCY+DhITFVZTcavHIX14bSOniBrQubFzP4i0swIDAQABAoIBAAVVY31FlfjXgY9a\ntYWWB7FR8SkYIr11/hXREVWrvHN4lnKXgW/RqVULg9ePCWWobdRdIUZfFPmZRtos\nBlfwgJTgWvjqsiNF3MQhKgfbddo5+78Xygat8kgCyOzdrBPoQ2+XBxA5B2NAG/Le\nue6JukFSKM9fec5d4yEfKE1tGLG42cYhR7zNMfrhsL+txT3/DWEDDJmho6zr9HGw\nfY0viJ8cia2asjjbNGKHc/3nltyYMGrDY1Vj2z++nRelztcd+LK7TwdCixIhkh71\nlhzcXWZ9ilDXrdhbOyOGmKF16ebhThDfeu9bO06/bAkDl30HbnBj5dJ1bsghUNfl\nuU/YwykCgYEA8126jS8M19mCttIJs6lgt6maroGYB3e86Q2Rzu33ikarQQ6NNJ4O\nQfr1OaZ/GHuVheAl3s9lZ+GFDAoQovJ/NjmJtO6fyVgBRgQDRwi02Bt+h3iA+xgP\nhGR9chTVUoYDFBM4UhmiL7Vc03Ki212YkcPZc7EUixlVe9Pe9W545I8CgYEA7CdB\nYP9fhfo+GVegZ3vjR5SP3olNnFWp9oJSCg4+ihLUYKSTYlff0q7kzBGgFg2RXhac\ncN65x/hzOtznNncjMImSdgX4x5vi7DII8YF5H8797Ms5C7rSShGs1L+FaXOea4tg\nnXE8wOiebhgoScZRcjrkmaOu4vU/0/VZR8shZ50CgYBTH/OlX6nCXHASZAGeVT9M\n3GiSLH+yJUroS5M/G/cOSv8ZtI+0pjv2e3KhY2ZMBYJX/OzSgwJ/Df+00gdGsQ+U\nhOitXUhErIOa16oK7EVg/1sjiJx9p4U9UlmqysTmcBHDHKGDIXBNXWQ8cQ6BYSHI\nwB2ZL6X1sQyKxB6GtFokrwKBgGP3zi5gjLBrmaQiuw1znWfs1OZwm0El5lgrHM2S\n8BiFFhB/OsDz0BUg4kwc3fbX8YSx77G8J0smuqjdYKdm0ae3ZR+/MWxWaj5wg+aw\nV3UGq+l0sgZsJJ8kUlSRasmUHykJjHG5wO0sy/xxD4UDhfDkS2daqir7hPSWNSA2\nNkLlAoGAWH+hJJNj8qs0F/a58mrZyjctVnG/7hWvyMd4BBdJxrP9CYdri2FjqX1P\nMhyvn2dzSZZ9+1lfLoZaCcFjwBZl9IIP3UtBnxkRynm6mFcP5+ssO2pqkAEIgwOH\neyHrdMwOPDzJmIAN77Q89m+UkfJ5WLPtkqoRm7MARIrG//5k+m4=\n-----END RSA PRIVATE KEY-----\n"
    cert: "-----BEGIN CERTIFICATE-----\nMIIE3jCCAsagAwIBAgIUcqwTfiRBVY1BTR4NJLPE/eL4cbowDQYJKoZIhvcNAQEL\nBQAwfTELMAkGA1UEBhMCVk4xEDAOBgNVBAgMB0RhIE5hbmcxEDAOBgNVBAcMB0Rh\nIE5hbmcxDDAKBgNVBAoMA0dBRTEXMBUGA1UEAwwOZ2FlLWd3LnN5c3RlbXMxIzAh\nBgkqhkiG9w0BCQEWFGtob2FkYXV0YXlAZ21haWwuY29tMB4XDTIyMDMwODA4MDQx\nNVoXDTI3MDMwNzA4MDQxNVowfTELMAkGA1UEBhMCVk4xEDAOBgNVBAgMB0RhIE5h\nbmcxEDAOBgNVBAcMB0RhIE5hbmcxDDAKBgNVBAoMA0dBRTEXMBUGA1UEAwwOZ2Fl\nLWd3LnN5c3RlbXMxIzAhBgkqhkiG9w0BCQEWFGtob2FkYXV0YXlAZ21haWwuY29t\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA4H+5aJUq+83BATH2gyHq\nhMpQaCAy50sQky4P59eSshJmyo5kLzRPXbGNvbgkSU1bYfym96xeKNE2/VldODSz\nHUGUBYkiW77lhvnxXskzaV2MwUe0xfSmDlC4F3IY7ClTVhE0++eaGzX2S75dRNXf\n8kHJ/mceuG1riAV+3OFGAziKrRx2qY/YVO6gDHu6GaPqNTGOol23S8dyfnNsvpF2\n8UiESshuxNbF3PWQ4FXlEh8AElltkWE5UndYibnxkeLSvIjPI4yeN5KvldsSTcCC\nKxfMSqGkLada1dAzb/vsm/I4IGnhYCY+DhITFVZTcavHIX14bSOniBrQubFzP4i0\nswIDAQABo1YwVDAfBgNVHSMEGDAWgBSjC7WGFbq1f87GkCl700Y/rme91DAJBgNV\nHRMEAjAAMAsGA1UdDwQEAwIE8DAZBgNVHREEEjAQgg5nYWUtZ3cuc3lzdGVtczAN\nBgkqhkiG9w0BAQsFAAOCAgEAemBzSiBtFnoT5VA861fviQ9F4vEihVjN/fTsh/YO\nJ/q3+hAqjhKY5hnX3QCMZCC9g7YU1mR89kmeHVUdiTA59Zq6hkz6gyyvM104O4p3\nfV+KHAc9UHXMt1LMxxTshrdInPkQ50Z61EX+bqlDAN8rKdqMpmd41Ewwa13wB0c5\nHaUv+Y3XE0BHe5yLuF1IaUjtwQui3+VoDoA67EmkdaWRKVhnF1e538lEkyRj23Ok\nye2clpywX0XdGKmd9YA9pomNYDOYvFaKpN+Ah/8LmNRUdaiM9/0DOYm24Tm4JxJb\nAsUY6Cgiib9xqQbxXMdYp9UIiJQw+LEp0tHdMz1ff0onFIQXI94sdEOuQROHUYXJ\nA+NOmK4PZXvxufLEMTWDDYM5VYkb8/PcgntcPNAIsAaMsSRZ1noG+h4SbWvs8VOy\nZJ1eCIne2HmTbTCwJ6Xp8JIkfAE6CMP++UrW/R5C5S4oKOEOkFXE+/i0SeMhWj90\n/zh8E0MYxjPR9gqjeoxSJHWyluokUAeuZ/ep6hkPrKQ5ahkQ23BNwKD1Zbr4TwAP\nvhfpgFOBJeCwGdoANoX8qxj1UFau8+yACFpiVg2HhjdLc+AM7GOU/HH/McDeFLEA\nSvSl2QjtHVX4w9qeibqpmgTaeM/LGHMtqUr/mCujFCGAop3oRAjBqysRh5751QVl\nWSY=\n-----END CERTIFICATE-----\n"
services:
- name: api-service
  host: gae-gw.systems
  port: 443
  connect_timeout: 60000
  protocol: https
  read_timeout: 60000
  retries: 5
  write_timeout: 60000
  routes:
    - name: api-route
      methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      paths:
        - /api
      protocols:
      - https
      regex_priority: 0
      strip_path: false
      preserve_host: false
