_format_version: "2.1"
_transform: true


# Config Consumers and JWT for consumers

consumers:
- username: gmm

jwt_secrets:
- consumer: gmm
  algorithm: RS256
  key: GAE
  rsa_public_key: "-----BEGIN PUBLIC KEY-----\nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA1MtRnSG0FT5BvJWjrieH\nesissdmUVsxal/p8s+2AiV+TtxI2R6PGnFMMOsz1s3/Xs5cMdYml1voKowHNF0+x\nhMO63vh+VfQOOI4TLAQMAMJgacftWEuuj7PbZfER6hu4xtKhJyMxISKrhEkMhkNb\nr652clLP+elWjiHNnk5J6rzyj7WZmjeQIZafRtWkPhlOxlHJV/8iaIZwZ/igvAhh\nr8Hls0b6E5Y4BA1oCMhelSffUj/aGAQwAagUkRhY6SMJ00oMfk4WAXLLcAtPHMeG\nvRxMHawBddSr4ozNdqtVjNrWfK18r4o8sAc709rtdGdwLUlBgQQTovFc985A4rQ3\nOdVz0O0umT0WygSyOfnQPIea/ixuekYUl4O5uQie8WErh1STEYPZk0I0Rt5/fwYX\n6R5uHIIhU5M3GQXQoy8gnWzDhyeNnkxPT04a6QhdXMOPA+8ORcKtXONpgZMLZBAP\nK8egK6LxfRxLJ5vtnGbzgnZj7J5MiizsZDn3b80R8pltynEkKiPmALuVbuz6iEie\nON8TDCSI5R0VLr1AJXfjDJD7bS6WaIaB31HHfUtEZImD88VzgddqNBLcwy28IUBF\nwnoyjZPwlxQxJaOqBecR7zZrHYRHK0MjV9PHJB3X+m0R7JWpxhjjhdbuiANV3xNg\ngI7Qy8bSZgHl4DE5OdxheWsCAwEAAQ==\n-----END PUBLIC KEY-----\n%"

plugins:
- name: jwt
  enabled: yes
  service: api-service
  config:
    secret_is_base64: false
    header_names: ["Authorization"]
    key_claim_name: iss
    run_on_preflight: true
    claims_to_verify:
      - exp

- name: rate-limiting
  config:
    second: 5
    hour: 10000
    policy: local
    fault_tolerant: true
    hide_client_headers: false
    redis_ssl: false
    redis_ssl_verify: false

# Config for Proxy cache request
- name: proxy-cache
  config:
    response_code:
    - 200
    request_method:
    - GET
    - HEAD
    content_type:
    - text/plain
    - application/json
    cache_ttl: 300
    strategy: memory

# Config Services và Routes
certificates:
  - snis:
      - name: gae-gw.systems
    key: "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDYF410UsZDLjy1\nGDhK+5ROro8Ag5PrtjfoxrENVAXG6CQPZc1vtHmIP6JnUxfenru8Ipm0at4MrETf\nu/t1WUn8nUqUi6aHTOYE5wh+GpqjVYhEsiZCSc21ajSimJxj6twpQbmqBLmg+qvN\nm8uHyFr3u1dH8NfRzq9zl0Vvz1q80MbXfbVNzUfywAhbgksVkR+eB+50obycQo+T\nmpHU8RXxN1IDwz4tmAaa3r58a+YBYq9Yjihhw6bwRh7uPT9dk31E0Dj8Cj8tvRHc\nmdhEiGGZC7AEKIwMUrrR6NDfauB+FsmJeLKOLms7Q5xZMz9HBDqOqQC+I6s7V7xF\nQnHUSX8zAgMBAAECggEABUUlx7Amcl2pULKuL3NNSFH3iN1XToiwz7Yw0TtlsgEt\nXUwao4kflv6+TjjM5zqwfMPMmIWBXtvAs5guZ3aYWFcvCh+8cvuhdyh59jazOMfi\n5+dUXt9/6yxo64zp8Nc51q5qAccrDnhZQk10vEiwTJm+ujFvLLMWvQHzyT33Cjhz\nHtsvEgZrDkikysUxTOtVNjG+KUWeL/mRxeikqm6Jl5X0nnbjzr6XwTlc34dNfHT3\nlNQ1BMFK9AHTcGAOOJz6pPPJuRy3wdA8aTN7uodBDCm1T9eE6PF8RoYWTzw6i6Sf\ns5OIJKYaV8ZCD5RB+6SjOAKffjJ127HeRM3gpOx/0QKBgQD3mXB8HIeVtJkun0RT\nodHo0niOMv+Z9mgj8tMbxRel9qNP+5i3p0S0PM6AHlwi4NlNG5kZE0xSXkJ4CXKq\nGLr1mcmu+wBDez29GgLFkqpovjYPjEbNYy2erMcxeps9UQfezd2IzcsOw6LVSr+q\ng0gPuBMYUzqtzUAml27iSPtuSQKBgQDfbHOHRFxR+hNZ9nA/ZwuzDbdcW0ugBFZS\nucB7Y4fa81YY7ACEqUjUuBydQcpoWdtvuYwsyIRMFj2dQGGGX4Ia+qp+wUZ+akNk\ni+/RE/IB6uPpk5B5IKxBdmJ2qOcOj8z60wGpUnlpg4tXcjzfyryCgYJJdEK6WULI\nPMdQ82PxmwKBgQCodxco6wR5oMKlDSqhOLYpEqOCJULyT8y1wO9Qsr6PZovhzM8x\nDjdZ5xGd7IpGFPTlWQTHIfFJDedt4wfIokD7AKNQUmnwgDcWpk8CfPNDh0AjPg+i\niXutveNeUAy2IJ8ZQrsb7OHfbs8pDs3wR5jNUTJ015RSUxf16g1BG+UvOQKBgH+k\nFMhljJyk0uNlgDEorK1pm6Se37CWab6vMkEL1rSGqlxoj886a0pjuK06xekh1NSa\nW3PGRpa1ahPpkQ3UiJ7jL/5kauKT0Najf6mhzHO9/uEVlcctnFt1x8Dks8RE8SUm\n4V8bqBNYvIWD1TVBPLsORCG00t5lWlrNJk2gDywbAoGBAIhgryq8BqQkakyv2ji9\n9+n9kcVOkhlZLt9j4pGPrn3KOls/WtjxaPy9fWcOWzxxQnxKb2raYIMJekIdjnf1\n/CX3jE49GEvv9IyDnyil5GismykRCUtz6xMezlSYLwY/fFP786VOkczauw0oWsvm\nTRm0T8XoaEOVz2/QUfWfE1ms\n-----END PRIVATE KEY-----\n"
    cert: "-----BEGIN CERTIFICATE-----\nMIIEFTCCAv2gAwIBAgIUBRE1IQQ8pLLWLLq9qkzMdVELJkAwDQYJKoZIhvcNAQEL\nBQAwgagxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQH\nEw1TYW4gRnJhbmNpc2NvMRkwFwYDVQQKExBDbG91ZGZsYXJlLCBJbmMuMRswGQYD\nVQQLExJ3d3cuY2xvdWRmbGFyZS5jb20xNDAyBgNVBAMTK01hbmFnZWQgQ0EgYjJj\nYTA3Yzk1ZjVhZWI0YTcxNmFhZTBkMmE1MGFmMzMwHhcNMjIwMzA4MDg1NDAwWhcN\nMzIwMzA1MDg1NDAwWjAiMQswCQYDVQQGEwJVUzETMBEGA1UEAxMKQ2xvdWRmbGFy\nZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANgXjXRSxkMuPLUYOEr7\nlE6ujwCDk+u2N+jGsQ1UBcboJA9lzW+0eYg/omdTF96eu7wimbRq3gysRN+7+3VZ\nSfydSpSLpodM5gTnCH4amqNViESyJkJJzbVqNKKYnGPq3ClBuaoEuaD6q82by4fI\nWve7V0fw19HOr3OXRW/PWrzQxtd9tU3NR/LACFuCSxWRH54H7nShvJxCj5OakdTx\nFfE3UgPDPi2YBprevnxr5gFir1iOKGHDpvBGHu49P12TfUTQOPwKPy29EdyZ2ESI\nYZkLsAQojAxSutHo0N9q4H4WyYl4so4uaztDnFkzP0cEOo6pAL4jqztXvEVCcdRJ\nfzMCAwEAAaOBuzCBuDATBgNVHSUEDDAKBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAA\nMB0GA1UdDgQWBBQLmwkrHlvT1q8vgpTb2zT8UiCxhzAfBgNVHSMEGDAWgBRj68TB\nvTscgRBry31ZoWqZt0/4hDBTBgNVHR8ETDBKMEigRqBEhkJodHRwOi8vY3JsLmNs\nb3VkZmxhcmUuY29tLzllN2I5Y2Q2LTM1NmUtNDBkOS04ZWJlLWY3NzU4NDRkMmIz\nYy5jcmwwDQYJKoZIhvcNAQELBQADggEBAHqF9EWVDttx19Z1/EgOoJBaDBiHCnIU\ncvw3Qt+1lOvFM2n83seYZiA6jMzqbe11zbmSomgOUY0RmU1seZhIkzqBPDpXI7ll\nOozKVru155FKYOdPur+60NJjtc6pxTNzyzYTLSZlr2bQ34/AK0cFkmeNvBgoqNku\nkRIdxgtTu4lf4WDXUpWP9IpOHa2oEjKAS9x58IJiz8iwfIms9LihA17ljJLA91mt\nUlXvVyun2Bqm/PdMh1OSDbXVw38hIHIL9ZV+4iuPRWqTgUVCB4skSlozFy7e8m41\n3uNEyMg6ATtUxoZIi1ahJKL16uD7nmklJ78cbfVrZo/aACOEcsYdJ+8=\n-----END CERTIFICATE-----\n"
services:
- name: api-service
  host: gae-gw.systems
  port: 443
  connect_timeout: 60000
  protocol: https
  read_timeout: 60000
  retries: 5
  write_timeout: 60000
  routes:
    - name: api-route
      methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      paths:
        - /api
      protocols:
      - https
      regex_priority: 0
      strip_path: false
      preserve_host: false
