# Generated by Django 3.2.10 on 2022-03-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_auto_20220302_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
