# Generated by Django 3.2.10 on 2022-03-26 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_oauth', 'init_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('january', models.IntegerField(blank=True, default=0)),
                ('february', models.IntegerField(blank=True, default=0)),
                ('march', models.IntegerField(blank=True, default=0)),
                ('april', models.IntegerField(blank=True, default=0)),
                ('may', models.IntegerField(blank=True, default=0)),
                ('june', models.IntegerField(blank=True, default=0)),
                ('july', models.IntegerField(blank=True, default=0)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
            ],
        ),
    ]
