# Generated by Django 3.2.10 on 2022-03-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_oauth', '0001_logrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrequest',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
