# Generated by Django 3.2.10 on 2022-01-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_oauth', '0002_auto_20220119_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='scopes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
