# Generated by Django 3.2.10 on 2022-01-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_oauth', '0001_initial'),
        ('custom_oauth', '0002_auto_20220119_2353'),
    ]

    operations = [
    ]
