# Generated by Django 3.2.10 on 2022-03-26 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_oauth', '0003_logrequest_uri'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logrequest',
            old_name='name',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='logrequest',
            name='application',
        ),
        migrations.RemoveField(
            model_name='logrequest',
            name='uri',
        ),
    ]
