# Generated by Django 3.2.10 on 2022-03-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_oauth', '0004_auto_20220326_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='logrequest',
            name='uri',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
