# Generated by Django 3.2.10 on 2022-03-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_oauth', '0005_logrequest_uri'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogUri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(blank=True, default='', max_length=400)),
                ('january', models.IntegerField(blank=True, default=0)),
                ('february', models.IntegerField(blank=True, default=0)),
                ('march', models.IntegerField(blank=True, default=0)),
                ('april', models.IntegerField(blank=True, default=0)),
                ('may', models.IntegerField(blank=True, default=0)),
                ('june', models.IntegerField(blank=True, default=0)),
                ('july', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='logrequest',
            name='uri',
        ),
    ]
