#api:
#  dashboard: true
#  insecure: true
#
#log:
#  level: ERROR
#
#entryPoints:
#  web:
#    # http
#    address: ":80"
#    http:
#      # https://docs.traefik.io/routing/entrypoints/#entrypoint
#      redirections:
#        entryPoint:
#          to: web-secure
#
#  web-secure:
#    # https
#    address: ":443"
#    http:
#      tls:
#        options: default
#
#  flower:
#    address: ":5555"
#
#  portainer:
#    address: ":9443"
#
#http:
#  routers:
#    web-secure-router:
#      rule: "Host(`gae-gw.systems`) || Host(`www.gae-gw.systems`)"
#      entryPoints:
#        - web-secure
#      middlewares:
#        - csrf
#      service: django
#
#
#    flower-secure-router:
#      rule: "Host(`gae-gw.systems`)"
#      entryPoints:
#        - flower
#      service: flower
#
#
#    portainer-secure-router:
#      rule: "Host(`gae-gw.systems`)"
#      entryPoints:
#        - portainer
#      service: portainer
#
#  middlewares:
#    csrf:
#      # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
#      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
#      headers:
#        accessControlAllowOriginList: ["*"]
#        hostsProxyHeaders: ["X-CSRFToken"]
#
#  services:
#    django:
#      loadBalancer:
#        servers:
#          - url: http://django:5000
#
#    flower:
#      loadBalancer:
#        servers:
#          - url: http://flower:5555
#
#    portainer:
#      loadBalancer:
#        servers:
#          - url: http://portainer:9443
#
#tls:
#  certificates:
#    - certFile: "/etc/traefik/acme/gae-gw-systems.crt"
#      keyFile: "/etc/traefik/acme/gae-gw-systems.key"
#      stores:
#        - default
#  options:
#    default:
#      minVersion: VersionTLS12
#      maxVersion: VersionTLS13
#  stores:
#      default:
#        defaultCertificate:
#          certFile: "/etc/traefik/acme/gae-gw-systems.crt"
#          keyFile: "/etc/traefik/acme/gae-gw-systems.key"
#
#providers:
#  # https://docs.traefik.io/master/providers/file/
#  file:
#    filename: /etc/traefik/traefik.yml
#    watch: true

api:
  dashboard: true
  insecure: true
  debug: true

log:
  level: ERROR

entryPoints:
  web:
    # http
    address: ":80"
    http:
      # https://docs.traefik.io/routing/entrypoints/#entrypoint
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    # https
    address: ":443"

  flower:
    address: ":5555"


certificatesResolvers:
  letsencrypt:
    # https://docs.traefik.io/master/https/acme/#lets-encrypt
    acme:
      email: "cuonglieu3256@gmail.com"
      storage: /etc/traefik/acme/acme.json
      # https://docs.traefik.io/master/https/acme/#httpchallenge
      httpChallenge:
        entryPoint: web

http:
  routers:
    web-secure-router:
      rule: "Host(`gae-gw.systems`) || Host(`www.gae-gw.systems`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

    flower-secure-router:
      rule: "Host(`gae-gw.systems`)"
      entryPoints:
        - flower
      service: flower
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

  middlewares:
    csrf:
      # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

    flower:
      loadBalancer:
        servers:
          - url: http://flower:5555

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
