api:
  dashboard: true
  debug: true

log:
  level: ERROR

entryPoints:
  web:
    # http
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    # https
    address: ":443"

  flower:
    address: ":5555"

  traefik:
    address: ":8080"

  kong:
    address: ":8000"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "cuonglieu3256@gmail.com"
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web

http:
  routers:
    dashboard:
      rule: "Host(`gae-gw.systems`) && PathPrefix(`/dashboard`)"
      service: api@internal
      entryPoints:
        - traefik
      middlewares:
        - auth
    web-secure-router:
      rule: "Host(`gae-gw.systems`) || Host(`www.gae-gw.systems`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django
      tls:
        certResolver: letsencrypt

    flower-secure-router:
      rule: "Host(`gae-gw.systems`)"
      entryPoints:
        - flower
      service: flower
      tls:
        certResolver: letsencrypt

    kong-secure-router:
      rule: "Host(`gae-gw.systems`) || Host(`www.gae-gw.systems`)"
      entryPoints:
        - kong
      service: kong
      tls:
        certResolver: letsencrypt

  middlewares:
    auth:
      basicAuth:
        users:
          - "admin:$2y$10$K1xogmLZKNVgPi8DCc0m4uwOsVElw.ww53fQR1vloHo9tomxdoI8i"
    csrf:
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

    kong:
      loadBalancer:
        servers:
          - url: http://kong:8000

    flower:
      loadBalancer:
        servers:
          - url: http://flower:5555

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
