name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: [ "main", "develop" ]
    paths-ignore: [ "docs/**" ]

  push:
    branches: [ "main", "develop" ]
    paths-ignore: [ "docs/**" ]


jobs:
  Linux:
    name: Validate API spec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - uses: kong/setup-inso@v1
        with:
          inso-version: 2.4.0
      - name: Run test suites
        run: inso run test "Test Token" --env "OpenAPI env" --ci
      - name: Generate declarative config
        run: inso generate config "Test Token" --type declarative --ci
